# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.1
    restart: always
    volumes:
# 설치 경로 수정 /data/mariadb_data
      - '/data/mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
#   image: docker.io/choipro/redmine:4.2.3-5plugins
    image: docker.io/choipro/redmine:4.2.3-7plugins
    restart: always
    ports:
# 설치 포트 수정 8080     
      - '8081:3000'
    volumes:
# 설치 경로 수정 /data/redmine_data 
      - '/data/redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine

